# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BannerCollectionViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BannerCollectionViewDemo
  pod 'ASPVideoPlayer', '6.1.2'
end
